### ISSUE TITLE
bump version number to reflect logging level change?

### ISSUE THREAD

**Issue by sharmarahul** [allure-framework/allure-ruby-adaptor-api#11]
Shouldn't the version number be updated for the change in logging level?

**Comment by smecsia** [comment]
@sharmarahul Ok. let's make a newer release.

**Comment by sharmarahul** [comment]
@smecsia because the version number was not updated, bundle update would not pick up the change. Was this change pushed to rubygems? I don't think so

**Comment by smecsia** [comment]
@sharmarahul I've pushed version 0.6.7 to rubygems

**Comment by sharmarahul** [comment]
Thanks @smecsia. Will you be able to update the allure-rspec dependency to the new version as well or do I create a separate issue for it?

**Comment by smecsia** [comment]
@sharmarahul I've just released it as well

**Comment by sharmarahul** [comment]
Thanks @smecsia

**Comment by smecsia** [comment]
you are welcome
