### ISSUE TITLE
Add bindings for Label type 'tags' which is a core part of Cucumber. 

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-ruby-adaptor-api#19]
Hey,

Some folks who are using the allure-cucumber repo are very interested in getting cucumber tags to show in the allure XML report. The add that functionality, it would require allure-core be updated to support a label type called 'tags'. We would then extend that api in allure-ruby-adaptop-api

From this attached issue, I can see the functionality is available in allure-core-java.
https://github.com/allure-framework/allure-core/issues/764

**Comment by smecsia** [comment]
@tk8817 From your comment in allure-cucumber ([#32](https://github.com/allure-framework/allure-cucumber/issues/32)):
> I would be happy to make a PR for this in allure-cucumber, however, the required methods are not exposed in the ruby API bindings :(

I actually don't understand clearly what do you need from ruby adaptor api. [start_test](https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb#L30) and [start_suite](https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb#L17) methods allow to provide any labels you want as a second argument. What methods do you need from the api to be able to send a PR to allure-cucumber?

**Comment by tk8817** [comment]
@smecsia - seems like my initial reading of the code was incorrect, I missed that this could be set as an argument during start_test & start_suite. 

Thank you for the very detailed response, I will close this issue and start work on a PR for the allure-cucumber formatter.

Thanks

**Comment by tk8817** [comment]
@smecsia -- Looking at the code again (and the linked RSpec code) - I think there is a disconnect on what is being asked for. 

```ruby
    ALLOWED_LABELS = [:feature, :story, :severity, :language, :framework, :issue, :testId, :host, :thread]
```

We are not trying to hook into an specific label type, we are seeking a generic label where all cucumber tags would be dumped. The value would be set to whatever the user passed in the cucumber scenario. 

Based on what i see above, setting these labels seem to be for a specific purpose and cause different effects. In the cucumber community tags do not have any standard/inherit purpose. They only gain purpose when combined with additional code in cucumbey.yml or hooks.rb. As such, all cucumber reporting tools treat tags as a generic collection of items / information points. 

```ruby
@ready_for_testing
Feature: Sample

  @lab_only @english_only
  Scenario: Example
    Given passing

  @known_bug
  Scenario: Another Example
    Given passing

  @flakey_test @fix_in_next_sprint
  Scenario: Yet another Example
    Given passing

  @ignore
  Scenario: And yet another Example

**Comment by smecsia** [comment]
@tk8817 Once again. Please look closely at the source code. allure-ruby-adaptor-api does not limit the label names within itself. My example was from allure-rspec project, which does not affect the api. 
Besides that there is a [limitation of label names within allure-core](https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd#L154-L166). AFAIK you cannot use custom labels in Allure for now in general. That's why I initially summoned @baev.

**Comment by tk8817** [comment]
this needs to be fixed in allure-core. An indexable tag type which takes anything as input
