### ISSUE TITLE
Unable to generate ruby based allure reports

### ISSUE THREAD

**Issue by ShettyA** [allure-framework/allure-ruby-adaptor-api#20]
Failing to generate alllure reports. Trying out a basic example. Am I missing something here?
Sample test code
```ruby

require 'test/unit'
require 'allure-ruby-adaptor-api'

class StringTest < Test::Unit::TestCase

  def test_length
    s = "Hello, World!"
    assert_equal(13, s.length)
  end

end

AllureRubyAdaptorApi.configure do |c|
  c.output_dir = "/reports"
end

builder = AllureRubyAdaptorApi::Builder
builder.start_suite "StringTest", :severity => :normal
builder.stop_suite "StringTest"
builder.build!
```

**Comment by smecsia** [comment]
@ShettyA You must start test cases as well as test suites. Your problem is in [this condition](https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb#L156).

**Comment by smecsia** [comment]
Closing this for now. Feel free to reopen if you have any additional problems.

**Comment by ShettyA** [comment]
You are right. The following worked.
`
require 'test/unit'
require 'allure-ruby-adaptor-api'

class StringTest < Test::Unit::TestCase

  def test_length
    s = "Hello, World!"
    assert_equal(13, s.length)
  end

end

# AllureRubyAdaptorApi.configure do |c|
#   c.output_dir = "/reports"
# end

builder = AllureRubyAdaptorApi::Builder
builder.start_suite "StringTest", :severity => :normal
builder.start_test "StringTest", "test_length", :severity => :critical
builder.stop_test "StringTest", "test_length", :status => :broken, :exception => Exception.new("some error")
builder.stop_suite "StringTest"
builder.build!
`

**Comment by NavyaGunde** [comment]
This is exactly my code.  I still have issues with this. It executes fine when I run this from Visual Studio Code.  It also generates the XML file.

<pre>
<code>
require 'aws-sdk'
require 'allure-ruby-adaptor-api'
require 'test/unit'

class StringTest < Test::Unit::TestCase
    def test_length
      s = "Hello, World!"
      assert_equal(13, s.length)
    end
end

builder = AllureRubyAdaptorApi::Builder
builder.start_suite "StringTest", :severity => :normal
builder.start_test "StringTest", "test_length", :severity => :critical
builder.stop_test "StringTest", "test_length", :status => :broken, :exception => Exception.new("some error")
builder.stop_suite "StringTest"
builder.build!
</code>
</pre>

The XML looks like below. I've multiple questions here.
1. Why does the test status shows as broken in the XML below.
2. Why is there a failure message.
3. When this XML is converted into the HTML report using Command Line, the HTML report is showing as 0 test cases. Why?

<pre>
<code>
&lt;?xml version="1.0"?&gt;
&lt;ns2:test-suite xmlns="" xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1505627368257" stop="1505627368257"&gt;
  &lt;name&gt;StringTest&lt;/name&gt;
  &lt;title&gt;StringTest&lt;/title&gt;
  &lt;test-cases&gt;
    &lt;test-case start="1505627368257" stop="1505627368257" status="broken"&gt;
      &lt;name&gt;test_length&lt;/name&gt;
      &lt;title&gt;test_length&lt;/title&gt;
      &lt;failure&gt;
        &lt;message&gt;some error&lt;/message&gt;
        &lt;stack-trace/&gt;
      &lt;/failure&gt;
      &lt;steps/&gt;
      &lt;attachments/&gt;
      &lt;labels&gt;
        &lt;label name="severity" value="critical"/&gt;
        &lt;label name="thread" value="20044420"/&gt;
        &lt;label name="host" value="GUNDE1"/&gt;
      &lt;/labels&gt;
      &lt;parameters/&gt;
    &lt;/test-case&gt;
  &lt;/test-cases&gt;
  &lt;labels&gt;
    &lt;label name="severity" value="normal"/&gt;
    &lt;label name="thread" value="20044420"/&gt;
    &lt;label name="host" value="GUNDE1"/&gt;
  &lt;/labels&gt;
&lt;/ns2:test-suite&gt;
</code>
</pre>
