### ISSUE TITLE
confusing type in add_attachment method

### ISSUE THREAD

**Issue by xiaoxinghu** [allure-framework/allure-ruby-adaptor-api#7]
I assume the type you are expecting for parameter `file` in option `opts` is `File`. But what does [this](https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb#L78) mean? File type does not have `basename` instance method. Am I missing something?

**Comment by smecsia** [comment]
You're right, this seems to be mistake. It should be `File.basename file`. Could you send a PR?

**Comment by sharmarahul** [comment]
@smecsia @xiaoxinghu I guess the PR for the issue above has already been merged followed by mine in which I added parentheses to fix the syntax error, however, I now have no screenshots in my report. I get the following error: 
```NoMethodError: private method `debug' called for nil:NilClass
    occurred at /Users/sharmrw1/.rvm/gems/ruby-2.2.0/gems/allure-ruby-adaptor-api-0.6.8/lib/allure-ruby-adaptor-api/builder.rb:87:in `add_attachment'```

**Comment by sharmarahul** [comment]
The reason there are no attachments is because I am using the output dir to save my screenshots so it gets wiped out using the clean_dir config. With file now using File.basename, it doesn't know where the screenshot is anymore

**Comment by sharmarahul** [comment]
@smecsia I have sent you a PR to fix the above error. @LOGGER should be LOGGER

**Comment by sharmarahul** [comment]
@smecsia I should have bumped up the version in my PR as well. Would you mind bumping up version for the @LOGGER fix and updating dependency in ```allure-rspec```? I can send another PR if you'd like!

**Comment by smecsia** [comment]
@sharmarahul I've pushed 0.7.4 to rubygems.
